version: '3.8'

services:

  mysql:
    image: mysql:8.0.28
    container_name: mysql_1
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: masterBet
      MYSQL_PASSWORD: masterBet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monitorBanca_db

  jaeger:
    image: jaegertracing/all-in-one:1.31
    container_name: jaeger_1
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411